### ISSUE TITLE
RFC

### ISSUE THREAD

**Issue by javierbertoli** [netmanagers/packages-formula#1]
@aboe76, @vutny, sorry to bother. What do you think, is this formula worth adding to the saltstack-formulas' repos? If so, do you think the name `simpack` is ok? I thought also of `packager` and `spm` (simple package manager), but both sounded kinda misleading to me, as it's not a 'packager' but a packages manager, and spm is confusing with Salt Package Manager.

Your comments are welcome. (if you know of another way of having some kind of PM, it'll be also welcome 😄)

**Comment by vutny** [comment]
@javierbertoli Thanks for pointing me to this, looks really great!
I would like to try it. Definitely it should be a part of @saltstack-formulas.

Just my opinion, but maybe `simpack` is not the best name here. It manages packages, although it does not bring in any new "package manager". By the way, the name is already taken by some 3D simulation software 😄 
https://sourceforge.net/projects/simpack/
That could confuse somebody.

How about something as simple as `packages-formula` or `installer-formula`?

**Comment by javierbertoli** [comment]
Great, I didn't even realize that a simpack thing already exists 😄
Renamed to `packages-formula`, and [added it to the "saltstack-formulas" account](https://github.com/saltstack-formulas/packages-formula)

Thanks for your comments, @vutny !
